[package]
name = "acp"
version = "0.5.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/sourcenetwork/defradb.rs"
description = "Access control policy types and policy YAML parsing"

[dependencies]
identity = { path = "../identity" }
zanzibar = { path = "../zanzibar" }
async-trait.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
serde_yaml.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true
