//! Client-side response types for JSON-RPC deserialization.

use alloy_primitives::{Address, B256, Bytes, U256};
use serde::{Deserialize, Serialize};

/// Transaction receipt returned by `eth_getTransactionReceipt`.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TransactionReceipt {
    /// Transaction hash.
    pub transaction_hash: B256,
    /// Transaction index in block.
    #[serde(with = "hex_u64")]
    pub transaction_index: u64,
    /// Block hash.
    pub block_hash: B256,
    /// Block number.
    #[serde(with = "hex_u64")]
    pub block_number: u64,
    /// Sender address.
    pub from: Address,
    /// Recipient address.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub to: Option<Address>,
    /// Cumulative gas used in the block up to this tx.
    #[serde(with = "hex_u64")]
    pub cumulative_gas_used: u64,
    /// Gas used by this transaction.
    #[serde(with = "hex_u64")]
    pub gas_used: u64,
    /// Contract address created (if any).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contract_address: Option<Address>,
    /// Logs generated by the transaction.
    pub logs: Vec<Log>,
    /// Logs bloom filter.
    pub logs_bloom: Bytes,
    /// Transaction type.
    #[serde(rename = "type", with = "hex_u64")]
    pub tx_type: u64,
    /// Status (1 = success, 0 = failure).
    #[serde(with = "hex_u64")]
    pub status: u64,
    /// Effective gas price.
    pub effective_gas_price: U256,
}

/// Log entry from a transaction receipt.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Log {
    /// Emitting contract address.
    pub address: Address,
    /// Indexed log topics.
    pub topics: Vec<B256>,
    /// Non-indexed log data.
    pub data: Bytes,
    /// Block number containing this log.
    #[serde(with = "hex_u64")]
    pub block_number: u64,
    /// Transaction hash.
    pub transaction_hash: B256,
    /// Transaction index in block.
    #[serde(with = "hex_u64")]
    pub transaction_index: u64,
    /// Block hash.
    pub block_hash: B256,
    /// Log index in block.
    #[serde(with = "hex_u64")]
    pub log_index: u64,
    /// Whether this log was removed due to a reorg.
    pub removed: bool,
}

/// Extended transaction receipt returned by `hub_getTransactionReceipt`.
///
/// Includes all standard receipt fields plus BLS identity info for native txs.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NativeReceipt {
    /// Transaction hash.
    pub transaction_hash: B256,
    /// Transaction index in block.
    #[serde(with = "hex_u64")]
    pub transaction_index: u64,
    /// Block hash.
    pub block_hash: B256,
    /// Block number.
    #[serde(with = "hex_u64")]
    pub block_number: u64,
    /// Sender address.
    pub from: Address,
    /// Recipient address.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub to: Option<Address>,
    /// Cumulative gas used in the block up to this tx.
    #[serde(with = "hex_u64")]
    pub cumulative_gas_used: u64,
    /// Gas used by this transaction.
    #[serde(with = "hex_u64")]
    pub gas_used: u64,
    /// Contract address created (if any).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contract_address: Option<Address>,
    /// Logs generated by the transaction.
    pub logs: Vec<Log>,
    /// Logs bloom filter.
    pub logs_bloom: Bytes,
    /// Transaction type.
    #[serde(rename = "type", with = "hex_u64")]
    pub tx_type: u64,
    /// Status (1 = success, 0 = failure).
    #[serde(with = "hex_u64")]
    pub status: u64,
    /// Effective gas price.
    pub effective_gas_price: U256,
    /// DID of the BLS signer (`None` for EVM transactions).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signer_did: Option<String>,
    /// Native transaction nonce (`None` for EVM transactions).
    #[serde(
        skip_serializing_if = "Option::is_none",
        default,
        deserialize_with = "opt_hex_u64::deserialize"
    )]
    pub native_nonce: Option<u64>,
}

/// Serde helper for optional hex-encoded u64 fields.
mod opt_hex_u64 {
    use serde::{self, Deserialize, Deserializer};

    pub(super) fn deserialize<'de, D>(deserializer: D) -> Result<Option<u64>, D::Error>
    where
        D: Deserializer<'de>,
    {
        let opt: Option<String> = Option::deserialize(deserializer)?;
        opt.map_or_else(
            || Ok(None),
            |s| {
                let s = s.strip_prefix("0x").unwrap_or(&s);
                u64::from_str_radix(s, 16)
                    .map(Some)
                    .map_err(serde::de::Error::custom)
            },
        )
    }
}

/// Node status returned by `hub_nodeStatus`.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NodeStatus {
    /// Chain ID.
    pub chain_id: u64,
    /// This validator's index.
    pub validator_index: u32,
    /// Total number of validators.
    #[serde(default)]
    pub validator_count: u32,
    /// Seconds since node started.
    pub uptime_secs: u64,
    /// Current consensus view number.
    pub current_view: u64,
    /// Number of finalized blocks.
    pub finalized_count: u64,
    /// Number of blocks proposed by this node.
    pub proposed_count: u64,
    /// Number of nullified rounds.
    pub nullified_count: u64,
    /// Number of connected peers.
    pub peer_count: u64,
    /// Whether this node is the current leader.
    pub is_leader: bool,
    /// Whether this node is backfilling historical blocks.
    #[serde(default)]
    pub backfilling: bool,
}

/// Serde helper for hex-encoded u64 fields in RPC responses.
mod hex_u64 {
    use serde::{self, Deserialize, Deserializer, Serializer};

    pub(super) fn serialize<S>(value: &u64, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&format!("{value:#x}"))
    }

    pub(super) fn deserialize<'de, D>(deserializer: D) -> Result<u64, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        let s = s.strip_prefix("0x").unwrap_or(&s);
        u64::from_str_radix(s, 16).map_err(serde::de::Error::custom)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn receipt_default() {
        let receipt = TransactionReceipt::default();
        assert_eq!(receipt.transaction_hash, B256::ZERO);
        assert!(receipt.logs.is_empty());
        assert_eq!(receipt.status, 0);
    }

    #[test]
    fn log_default() {
        let log = Log::default();
        assert_eq!(log.address, Address::ZERO);
        assert!(log.topics.is_empty());
        assert!(!log.removed);
    }

    #[test]
    fn node_status_default() {
        let status = NodeStatus::default();
        assert_eq!(status.chain_id, 0);
        assert!(!status.is_leader);
        assert!(!status.backfilling);
        assert_eq!(status.validator_count, 0);
    }

    #[test]
    fn node_status_serde_roundtrip() {
        let status = NodeStatus {
            chain_id: 1337,
            validator_index: 2,
            validator_count: 4,
            uptime_secs: 3600,
            current_view: 100,
            finalized_count: 50,
            proposed_count: 10,
            nullified_count: 5,
            peer_count: 3,
            is_leader: true,
            backfilling: false,
        };
        let json = serde_json::to_string(&status).unwrap();
        let parsed: NodeStatus = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.chain_id, 1337);
        assert!(parsed.is_leader);
        assert_eq!(parsed.finalized_count, 50);
        assert_eq!(parsed.validator_count, 4);
        assert!(!parsed.backfilling);
    }

    #[test]
    fn node_status_backward_compat() {
        let json = serde_json::json!({
            "chainId": 1337,
            "validatorIndex": 2,
            "uptimeSecs": 3600,
            "currentView": 100,
            "finalizedCount": 50,
            "proposedCount": 10,
            "nullifiedCount": 5,
            "peerCount": 3,
            "isLeader": true
        });
        let parsed: NodeStatus = serde_json::from_value(json).unwrap();
        assert_eq!(parsed.validator_count, 0);
        assert!(!parsed.backfilling);
    }

    #[test]
    fn receipt_deserialize_hex_fields() {
        let json = serde_json::json!({
            "transactionHash": "0x0000000000000000000000000000000000000000000000000000000000000001",
            "transactionIndex": "0x0",
            "blockHash": "0x0000000000000000000000000000000000000000000000000000000000000002",
            "blockNumber": "0xa",
            "from": "0x0000000000000000000000000000000000000001",
            "cumulativeGasUsed": "0x5208",
            "gasUsed": "0x5208",
            "logs": [],
            "logsBloom": "0x",
            "type": "0x2",
            "status": "0x1",
            "effectiveGasPrice": "0x3b9aca00"
        });
        let receipt: TransactionReceipt = serde_json::from_value(json).unwrap();
        assert_eq!(receipt.block_number, 10);
        assert_eq!(receipt.status, 1);
        assert_eq!(receipt.gas_used, 21000);
        assert_eq!(receipt.tx_type, 2);
    }
}
