//! ACP module — Zanzibar-style access control policies.

/// Solidity ABI interface for the ACP precompile.
pub mod abi;
/// ACP error types.
pub mod error;
/// Key prefixes and builders for ACP KV storage.
pub mod keys;
/// ACP domain types.
pub mod types;

use std::collections::HashMap;

use acp::Policy;
use error::AcpError;
use identity::Did;

use crate::types::BlockExecCtx;
use types::{
    AccessDecision, AccessRequest, AcpParams, AmendmentEvent, ContentType,
    GenerateCommitmentResult, Object, PolicyCmd, PolicyCmdResult, PolicyMarshalingType,
    PolicyRecord, RegistrationsCommitment, RelationshipRecord, RelationshipSelector,
};

type Result<T> = std::result::Result<T, AcpError>;

/// Access Control Policy module.
///
/// Manages Zanzibar-style relation tuples, policy CRUD, object registration,
/// and access checks. Business logic lives here; precompile and native-tx
/// shims are thin wrappers that decode arguments and forward to these methods.
#[derive(Clone, Debug)]
pub struct AcpModule {
    store: HashMap<Vec<u8>, Vec<u8>>,
}

impl Default for AcpModule {
    fn default() -> Self {
        Self::new()
    }
}

#[allow(dead_code)]
impl AcpModule {
    /// Create a new ACP module instance.
    pub fn new() -> Self {
        Self {
            store: HashMap::new(),
        }
    }

    // ── Msg handlers ────────────────────────────────────────────────────

    /// Parse, validate, and store a new access control policy.
    ///
    /// Flow:
    ///   1. Inject `creator` DID as the authenticated principal into the
    ///      engine context (Go: `utils.InjectPrincipal`). The engine
    ///      extracts this principal to set as policy owner.
    ///   2. Build `RecordMetadata` from execution context:
    ///      ```text
    ///      creation_ts = block_ctx.timestamp
    ///      tx_hash     = sha256(raw_tx_bytes)
    ///      tx_signer   = tx_ctx.signer
    ///      owner_did   = creator.to_string()
    ///      ```
    ///   3. Call `engine.create_policy(policy, marshal_type)` with the
    ///      metadata stored as a `SuppliedMetadata` blob on the record.
    ///      - Engine parses `policy` string according to `marshal_type`
    ///      - Engine runs the create-policy pipeline: transforms the policy
    ///        (adds default actor resource, discretionary relations,
    ///        decentralized admin, sorts, generates ID) then validates
    ///        (name non-empty via BasicRequirement, spec-conditional checks)
    ///      - Engine generates policy ID as a double SHA-256 hex digest.
    ///        Inner hash iterates per-resource in order:
    ///        `SHA256(name || for each resource { resource.name ||
    ///        for each relation { relation.name } ||
    ///        for each permission { perm.name || perm.expression } })`
    ///        Outer hash: `hex(SHA256(inner_hash || counter_string))`
    ///        where `counter_string` is the decimal representation of a
    ///        monotonic counter value
    ///      - Engine stores the transformed `PolicyRecord` (which may differ
    ///        from the input due to pipeline transforms)
    ///   4. Return the `PolicyRecord` from the engine response
    ///
    /// Reads: engine internal state (counter, schema validation)
    /// Writes: engine policy store (new PolicyRecord keyed by generated ID),
    ///         engine counter store (monotonic counter incremented)
    /// Ctx: block_ctx (timestamp for metadata), tx_ctx (tx_hash + signer for metadata)
    ///
    /// Errors:
    ///   - `AcpError::InvalidPolicy` if the policy string fails parsing or
    ///     schema validation
    ///
    /// The policy ID is a SHA-256 hex string generated by the engine, not
    /// by this method. The caller receives it back inside
    /// `PolicyRecord.policy.id`.
    #[allow(unused_variables)]
    pub fn create_policy(
        &mut self,
        creator: &Did,
        policy: &str,
        marshal_type: PolicyMarshalingType,
    ) -> Result<PolicyRecord> {
        todo!()
    }

    /// Replace a policy's definition, pruning relationships that no longer fit.
    ///
    /// Flow:
    ///   1. Inject `creator` DID as authenticated principal into engine context
    ///   2. Call `engine.edit_policy(policy_id, policy, marshal_type)`:
    ///      - Engine fetches existing policy by `policy_id`
    ///      - Engine extracts principal from context and verifies it matches
    ///        the existing record's `metadata.creator` (the policy owner)
    ///      - Engine parses and validates new policy definition, enforcing:
    ///        - `ImmutableSpecRequirement`: spec type cannot change on edit
    ///        - `PreservedResourcesRequirement`: existing resources must still
    ///          be present in the new definition
    ///      - Engine clones old record, updates policy/definition/marshal_type,
    ///        sets `metadata.last_modified = now` (preserves original creator
    ///        and creation_ts — metadata is NOT rebuilt)
    ///      - Engine prunes orphaned relationships for relation changes
    ///        within preserved resources (note: resources themselves cannot
    ///        be removed — PreservedResourcesRequirement rejects that)
    ///      - Engine stores updated `PolicyRecord`
    ///   3. Return `(relationships_removed, updated PolicyRecord)`
    ///
    /// Reads: engine policy store (existing policy + relationships)
    /// Writes: engine policy store (updated definition), engine relationship
    ///         store (deletes orphaned relationships)
    /// Ctx: block_ctx (for last_modified timestamp)
    ///
    /// Errors:
    ///   - `AcpError::PolicyNotFound` if `policy_id` does not exist
    ///   - `AcpError::Unauthorized` if `creator` is not the policy owner
    ///   - `AcpError::InvalidPolicy` if new definition fails validation
    ///     (including spec type change or missing existing resources)
    #[allow(unused_variables)]
    pub fn edit_policy(
        &mut self,
        creator: &Did,
        policy_id: &str,
        policy: &str,
        marshal_type: PolicyMarshalingType,
    ) -> Result<(u64, PolicyRecord)> {
        todo!()
    }

    /// Evaluate an access check and persist the decision.
    ///
    /// Flow:
    ///   1. Fetch policy via `engine.get_policy(policy_id)` — fail if not found
    ///   2. Call `engine.verify_access_request(policy_id, access_request)`
    ///      - Evaluates ALL operations against the Zanzibar relation graph
    ///      - All-or-nothing: every operation must pass or the whole request
    ///        is unauthorized
    ///   3. If access denied, return `AcpError::Unauthorized`
    ///   4. Build `AccessDecision`:
    ///      ```text
    ///      id          = sha256_base32(policy_id + creator + actor + creator_acc_seq
    ///                    + issued_height + creation_time + sorted(operations) + hash(params))
    ///      policy_id   = policy_id
    ///      creator     = creator.to_string()
    ///      creator_acc_sequence = account nonce (Go: accountKeeper.GetAccount; hub.rs: EVM account state nonce)
    ///      operations  = access_request.operations
    ///      actor       = access_request.actor.0.to_string()
    ///      params      = DecisionParams { decision_expiration_delta: 100,
    ///                    ticket_expiration_delta: 100, proof_expiration_delta: 50 }
    ///      creation_time  = block_ctx.timestamp
    ///      issued_height  = block_ctx.timestamp.block_height
    ///      ```
    ///   5. Store decision at KV prefix `"access_decision/" + id`
    ///   6. Return the `AccessDecision`
    ///
    /// Reads: engine policy + relationship stores, access decision params
    /// Writes: access decision store (`"access_decision/"` prefix)
    /// Ctx: block_ctx (timestamp, height), tx_ctx (for creator_acc_sequence)
    ///
    /// Errors:
    ///   - `AcpError::PolicyNotFound` if policy does not exist
    ///   - `AcpError::Unauthorized` if any operation in the request is denied
    ///
    /// The decision ID is deterministic — same inputs at the same block height
    /// with the same account sequence produce the same ID. The actor comes from
    /// `access_request.actor`, NOT from `creator`.
    #[allow(unused_variables)]
    pub fn check_access(
        &mut self,
        creator: &Did,
        policy_id: &str,
        access_request: &AccessRequest,
    ) -> Result<AccessDecision> {
        todo!()
    }

    /// Execute a policy command authenticated by the tx signer's DID.
    ///
    /// Flow:
    ///   1. Read module params from KV key `"p_acp"`
    ///   2. Inject `creator` DID as authenticated principal into engine context
    ///      (Go: `utils.InjectPrincipal` — called before dispatch, not per-variant)
    ///   3. Dispatch `cmd` to the appropriate handler variant.
    ///      Variants that write records build `RecordMetadata` from execution
    ///      context individually (e.g., SetRelationship, RegisterObject).
    ///      Read-only variants like DeleteRelationship build no metadata.
    ///
    ///      SetRelationship(rel):
    ///        - Engine validates policy exists, resource/relation defined,
    ///          creator is authorized (Zanzibar ownership rules)
    ///        - Engine stores relationship tuple, attaches metadata
    ///        - Returns SetRelationship { record_existed, record }
    ///        - Idempotent: re-setting existing relationship succeeds
    ///
    ///      DeleteRelationship(rel):
    ///        - Engine validates policy exists, creator is authorized
    ///        - Engine deletes the tuple if found
    ///        - Returns DeleteRelationship { record_found }
    ///        - Deleting non-existent relationship is not an error
    ///
    ///      RegisterObject(obj):
    ///        - Engine validates policy exists, resource defined,
    ///          object is NOT already registered
    ///        - Engine creates owner relationship (creator becomes owner)
    ///        - Returns RegisterObject { record } (the ownership tuple)
    ///        - NOT idempotent: re-registering returns error
    ///
    ///      ArchiveObject(obj):
    ///        - Engine validates creator is the object owner
    ///        - Engine flags object as archived, deletes all its relationships
    ///        - Returns ArchiveObject { found: true, relationships_removed }
    ///
    ///      UnarchiveObject(obj):
    ///        - Engine validates creator is the previous owner
    ///        - Engine clears `archived` flag on existing owner relationship
    ///          record and updates it in place (does NOT create a new tuple)
    ///        - Returns UnarchiveObject { record, relationship_modified }
    ///        - Idempotent: unarchiving active object succeeds
    ///
    ///      CommitRegistrations { commitment }:
    ///        - Validates policy exists via engine
    ///        - Validates commitment is exactly 32 bytes (SHA-256 Merkle root)
    ///        - Stores new `RegistrationsCommitment` at KV prefix `"commitment/"`
    ///          with autoincrement ID, expired=false,
    ///          validity=params.registrations_commitment_validity
    ///        - Returns CommitRegistrations { registrations_commitment }
    ///
    ///      RevealRegistration { registrations_commitment_id, proof }:
    ///        - Fetches commitment by ID from `"commitment/"` prefix
    ///        - Rejects if expired: error when `creation_ts + validity < now`
    ///        - Verifies Merkle proof against commitment root
    ///          (RFC 6962: leaf = SHA256(0x00 || policyId + resource + objectId + actorDID))
    ///        - If object unregistered: registers it (creator becomes owner)
    ///        - If object registered and commitment is OLDER than the
    ///          registration (commitment.block_height <= registration.block_height):
    ///          amends ownership, creates AmendmentEvent at `"amendment_event/"`
    ///        - If commitment is newer than registration: error (cannot amend)
    ///        - Returns RevealRegistration { record, event }
    ///
    ///      FlagHijackAttempt { event_id }:
    ///        - Fetches AmendmentEvent by ID from `"amendment_event/"` prefix
    ///        - Validates creator DID matches event's new_owner (the actor
    ///          who performed the RevealRegistration amendment)
    ///        - Sets hijack_flag = true on the event
    ///        - Returns FlagHijackAttempt { event }
    ///        - Idempotent: re-flagging succeeds
    ///
    /// Reads: engine stores, commitment store, amendment event store, params
    /// Writes: engine stores, commitment store, amendment event store
    /// Ctx: block_ctx + tx_ctx (for RecordMetadata on write variants)
    ///
    /// Errors: per-variant as described above; common errors include
    ///   PolicyNotFound, Unauthorized, InvalidInput
    #[allow(unused_variables)]
    pub fn direct_policy_cmd(
        &mut self,
        creator: &Did,
        policy_id: &str,
        cmd: PolicyCmd,
    ) -> Result<PolicyCmdResult> {
        todo!()
    }

    /// Execute a policy command authenticated by a JWS payload signature.
    ///
    /// Flow:
    ///   1. Read module params from KV key `"p_acp"` (needed for expiration checks)
    ///   2. Validate `content_type` is `ContentType::Jws` (reject Unknown)
    ///   3. Parse `payload` as JWS (Go uses `FullSerialize` / JSON format;
    ///      `jose.ParseSigned` accepts both compact and JSON serialization)
    ///   4. Unmarshal JWS payload as `SignedPolicyCmdPayload`
    ///      `{ policy_id, cmd: PolicyCmd, actor: DID, issued_height: u64,
    ///        issued_at: Timestamp, expiration_delta: u64 }`
    ///      (`issued_at` is client-generated metadata, not trusted for validation)
    ///   5. Decode actor DID as did:key, extract public key
    ///   6. Verify JWS signature against the extracted public key
    ///      (supports secp256k1/ES256K and ed25519)
    ///   7. Validate expiration_delta <= params.policy_command_max_expiration_delta
    ///   8. Validate not expired: block_height <= issued_height + expiration_delta
    ///   9. Replay check: compute payload_id = SHA256(jws_string) (full JWS string, not decoded payload)
    ///      - Read KV `"spc_seen/" + payload_id` → stored expire_height (8 bytes BE)
    ///      - If found AND expire_height >= current block_height → reject as replay
    ///      - If found AND expire_height < current block_height → delete stale entry
    ///  10. Store replay marker: `"spc_seen/" + payload_id` → BE(issued_height + expiration_delta)
    ///  11. Dispatch cmd variant (same as direct_policy_cmd) with actor DID
    ///      from the JWS payload as the authenticated principal
    ///
    /// Reads: params store, replay cache (`"spc_seen/"` prefix), engine stores
    /// Writes: replay cache, engine stores (per cmd variant)
    /// Ctx: block_ctx (for expiration checks + metadata)
    ///
    /// Errors:
    ///   - `AcpError::InvalidInput` if JWS parsing, payload unmarshal, or
    ///     DID decode fails
    ///   - `AcpError::Unauthorized` if JWS signature verification fails
    ///   - `AcpError::ExpirationDeltaTooLarge` if delta exceeds param limit
    ///   - `AcpError::CommandExpired` if block_height > issued_height + delta
    ///   - `AcpError::ReplayDetected` if payload_id already seen and not expired
    ///
    /// The actor is extracted from the JWS payload, NOT from `creator`.
    /// `creator` is the tx submitter (relay), not the authenticated actor.
    #[allow(unused_variables)]
    pub fn signed_policy_cmd(
        &mut self,
        creator: &Did,
        payload: &str,
        content_type: ContentType,
    ) -> Result<PolicyCmdResult> {
        todo!()
    }

    /// Execute a policy command authenticated by a bearer JWT token.
    ///
    /// Flow:
    ///   1. Parse `bearer_token` as compact-serialized JWS
    ///      (reject JSON serialization — security: prevents unprotected header attacks)
    ///   2. Extract and validate claims
    ///      `{ iss: DID, iat: unix_ts, exp: unix_ts, authorized_account: address }`.
    ///      All four required. exp must be >= iat.
    ///   3. Decode issuer DID as did:key, extract public key
    ///   4. Verify JWS signature against the issuer's public key
    ///   5. Check token not expired: block_ctx.timestamp.seconds <= exp
    ///   6. Check authorized_account matches `creator` (the tx submitter
    ///      must be the account authorized in the token)
    ///   7. Read module params, dispatch `cmd` with issuer DID as the
    ///      authenticated principal (same dispatch as direct_policy_cmd)
    ///
    /// Reads: params store, engine stores (per cmd variant)
    /// Writes: engine stores (per cmd variant)
    /// Ctx: block_ctx (wall-clock for token expiration), tx_ctx (signer for
    ///       authorized_account check)
    ///
    /// Errors:
    ///   - `AcpError::InvalidBearerToken` if JWS parsing, claim extraction,
    ///     or signature verification fails (Go: `ErrorType_BAD_INPUT`)
    ///   - `AcpError::Unauthorized` if authorized_account does not match `creator`
    ///   - `AcpError::InvalidBearerToken` if block time > exp (token expiration
    ///     is a sub-error of invalid bearer token in Go, not a separate type)
    ///
    /// The actor is the token's issuer DID, NOT `creator`. `creator` is the
    /// tx submitter authorized by the token. No replay protection — same
    /// bearer token can be reused until it expires. `policy_id` and `cmd`
    /// come from the message, not from the token.
    #[allow(unused_variables)]
    pub fn bearer_policy_cmd(
        &mut self,
        creator: &Did,
        bearer_token: &str,
        policy_id: &str,
        cmd: PolicyCmd,
    ) -> Result<PolicyCmdResult> {
        todo!()
    }

    /// Update governance-controlled module parameters.
    ///
    /// Flow:
    ///   1. Check `authority` matches the configured governance authority
    ///   2. Serialize `params` and store at KV key `"p_acp"`
    ///
    /// Reads: governance authority (configured at module init)
    /// Writes: params store (KV key `"p_acp"`)
    /// Ctx: none
    ///
    /// Errors:
    ///   - `AcpError::Unauthorized` if authority does not match
    ///
    /// No validation on param values — the caller is trusted (governance).
    /// `AcpParams` fields:
    ///   policy_command_max_expiration_delta: u64 (default 43200 blocks, ~12h)
    ///   registrations_commitment_validity: Duration (default 10 min wall time)
    #[allow(unused_variables)]
    pub fn update_params(&mut self, authority: &Did, params: AcpParams) -> Result<()> {
        todo!()
    }

    // ── Query handlers ──────────────────────────────────────────────────

    /// Fetch a policy by ID.
    ///
    /// Flow:
    ///   1. Call `engine.get_policy(id)` — propagate engine errors
    ///   2. If engine returns `None`, return `AcpError::PolicyNotFound`
    ///   3. Extract `RecordMetadata` from the record's `metadata.supplied.blob`
    ///   4. Return `PolicyRecord { policy, raw_policy, marshal_type, metadata }`
    ///
    /// Reads: engine policy store
    #[allow(unused_variables)]
    pub fn query_policy(&self, id: &str) -> Result<PolicyRecord> {
        todo!()
    }

    /// List all stored policy IDs.
    ///
    /// Flow:
    ///   1. Call `engine.list_policies()` to get all PolicyRecords
    ///   2. Skip any None/nil entries in the result set
    ///   3. Extract `policy.id` from each record
    ///   4. Return the IDs as Vec<String>
    ///
    /// Reads: engine policy store (full scan)
    ///
    /// Returns empty vec if no policies exist.
    /// Go implementation supports pagination; hub.rs returns all IDs
    /// (pagination can be added later if needed).
    pub fn query_policy_ids(&self) -> Result<Vec<String>> {
        todo!()
    }

    /// Filter relationships within a policy using a selector.
    ///
    /// Flow:
    ///   1. Call `engine.filter_relationships(policy_id, selector)` — passes
    ///      the policy ID string directly (no separate get_policy call at
    ///      keeper level; policy-not-found is handled inside the engine):
    ///      - `ObjectSelector`: Exact(Object), Wildcard, or ResourcePredicate(resource_name)
    ///      - `RelationSelector`: Exact(relation_name: String), or Wildcard
    ///      - `SubjectSelector`: Exact(Subject), or Wildcard
    ///   2. For each result, extract `RecordMetadata` from `record.metadata.supplied.blob`
    ///   3. Return Vec<RelationshipRecord>
    ///
    /// Reads: engine policy store + relationship store (filtered query)
    ///
    /// Returns empty vec if no matches (not an error).
    #[allow(unused_variables)]
    pub fn query_filter_relationships(
        &self,
        policy_id: &str,
        selector: &RelationshipSelector,
    ) -> Result<Vec<RelationshipRecord>> {
        todo!()
    }

    /// Verify an access request without recording a decision.
    ///
    /// Flow:
    ///   1. Resolve actor DID: if `access_request.actor.id` is an account
    ///      address, derive the `did:key` (Go silently replaces the actor ID
    ///      with a resolved DID when possible; on failure keeps the original)
    ///   2. Call `engine.verify_access_request(policy_id, access_request)`
    ///      - Evaluates ALL operations against the Zanzibar graph
    ///   3. Return true if all operations pass, false otherwise
    ///
    /// Reads: engine policy + relationship stores
    /// Writes: nothing (read-only, unlike check_access which persists)
    ///
    /// Returns false for denied access (not an error).
    /// Policy-not-found behavior is delegated to the engine (no explicit
    /// check at this level, unlike check_access which does check).
    #[allow(unused_variables)]
    pub fn query_verify_access_request(
        &self,
        policy_id: &str,
        access_request: &AccessRequest,
    ) -> Result<bool> {
        todo!()
    }

    /// Validate a policy definition without storing it.
    ///
    /// Flow:
    ///   1. Parse `policy` string according to `marshal_type`
    ///   2. Run through the create-policy pipeline (basic requirements +
    ///      spec-conditional checks)
    ///   3. Initialize zanzi engine and call `engine.validate_policy(parsed)`
    ///   4. If valid: return (true, "", parsed Policy)
    ///   5. If parse/pipeline failure: return (false, error_msg, Policy::default())
    ///   6. If zanzi-invalid: return (false, error_msg, populated Policy) —
    ///      note the Policy is populated even when invalid at this stage
    ///
    /// Reads: opens KV store for zanzi engine initialization (not fully
    ///   stateless despite being a "query" — the engine requires store access)
    ///
    /// Invalid policy is NOT an error — it returns (false, msg, ...).
    /// Only internal failures (zanzi init, engine errors) return Err.
    #[allow(unused_variables)]
    pub fn query_validate_policy(
        &self,
        policy: &str,
        marshal_type: PolicyMarshalingType,
    ) -> Result<(bool, String, Policy)> {
        todo!()
    }

    /// Fetch a previously recorded access decision by ID.
    ///
    /// Flow:
    ///   1. Read from KV prefix `"access_decision/" + id`
    ///   2. Deserialize as `AccessDecision`
    ///   3. If not found, return `Ok(None)` (Go returns nil Decision pointer)
    ///
    /// Reads: access decision store (`"access_decision/"` prefix)
    ///
    /// Not-found is not an error — returns `None`.
    #[allow(unused_variables)]
    pub fn query_access_decision(&self, id: &str) -> Result<Option<AccessDecision>> {
        todo!()
    }

    /// Check if an object is registered and return its owner.
    ///
    /// Flow:
    ///   1. Call `engine.get_object_registration(policy_id, object)`
    ///   2. If registered: extract owner RelationshipRecord with metadata,
    ///      return (true, Some(record))
    ///   3. If not registered: return (false, None)
    ///
    /// Reads: engine object registration store
    ///
    /// Unregistered object is not an error — returns (false, None).
    /// Policy not found propagates as engine error.
    #[allow(unused_variables)]
    pub fn query_object_owner(
        &self,
        policy_id: &str,
        object: &Object,
    ) -> Result<(bool, Option<RelationshipRecord>)> {
        todo!()
    }

    /// Fetch a registration commitment by its autoincrement ID.
    ///
    /// Flow:
    ///   1. Read from commitment store. Go uses raccoondb with application
    ///      prefix `"commitment/"` — raccoondb internally adds `"objs/"` for
    ///      its object storage, making the full KV path `"commitment/objs/"`.
    ///      If rolling our own keys, decide whether to replicate this layout
    ///      or use a simpler `"commitment/" + id` scheme.
    ///      Key is the u64 ID encoded as 8-byte big-endian bytes.
    ///   2. Deserialize as `RegistrationsCommitment`
    ///
    /// Reads: commitment store (application prefix `"commitment/"`, keyed by u64 ID)
    ///
    /// Errors:
    ///   - `AcpError::CommitmentNotFound` if ID does not exist
    #[allow(unused_variables)]
    pub fn query_registrations_commitment(&self, id: u64) -> Result<RegistrationsCommitment> {
        todo!()
    }

    /// Find registration commitments matching a commitment byte value.
    ///
    /// Flow:
    ///   1. Query raccoondb commitment store secondary index on `commitment` field
    ///   2. Materialize all matching `RegistrationsCommitment` records
    ///
    /// Reads: commitment store (application prefix `"commitment/"`, `commitment`
    ///   secondary index — same raccoondb layout note as `query_registrations_commitment`)
    ///
    /// Returns empty vec if no matches (not an error).
    /// Multiple commitments can share the same root (different actors/policies).
    #[allow(unused_variables)]
    pub fn query_registrations_commitment_by_commitment(
        &self,
        commitment: &[u8],
    ) -> Result<Vec<RegistrationsCommitment>> {
        todo!()
    }

    /// Generate a Merkle commitment and per-object proofs.
    ///
    /// Flow:
    ///   1. Validate policy exists via `engine.get_policy(policy_id)`
    ///   2. For each object: verify NOT already registered via
    ///      `engine.get_object_registration(policy_id, object)` — fail if any is
    ///   3. Build leaf values: for each object,
    ///      leaf_bytes = concat(policy_id, object.resource, object.id, actor.0.to_string())
    ///   4. Compute Merkle tree (RFC 6962):
    ///      leaf_hash  = SHA256(0x00 || leaf_bytes)
    ///      inner_hash = SHA256(0x01 || left || right)
    ///   5. Generate per-leaf audit proofs (aunt hashes)
    ///   6. Return `GenerateCommitmentResult`:
    ///      ```text
    ///      commitment     = 32-byte Merkle root
    ///      commitment_hex = hex::encode(commitment)
    ///      proofs         = Vec<RegistrationProof> (one per object, with
    ///                       merkle_proof, leaf_count, leaf_index)
    ///      proofs_json    = Vec<String> (JSON-serialized proofs)
    ///      ```
    ///
    /// Reads: engine policy + object registration stores
    /// Writes: nothing (pure computation)
    ///
    /// Errors:
    ///   - `AcpError::PolicyNotFound` if policy does not exist
    ///   - `AcpError::InvalidInput` if any object is already registered
    ///   - `AcpError::InvalidInput` if objects list is empty
    #[allow(unused_variables)]
    pub fn query_generate_commitment(
        &self,
        policy_id: &str,
        objects: &[Object],
        actor: &types::Actor,
    ) -> Result<GenerateCommitmentResult> {
        todo!()
    }

    /// List amendment events flagged as hijack attempts for a policy.
    ///
    /// Flow:
    ///   1. Query amendment event store by `policy_id` secondary index
    ///   2. Filter to events where `hijack_flag == true`
    ///   3. Return matching `AmendmentEvent` records
    ///
    /// Reads: amendment event store (`"amendment_event/"` prefix, `policy_id` index)
    ///
    /// Returns empty vec if no hijack events (not an error).
    /// Does not validate that the policy exists.
    #[allow(unused_variables)]
    pub fn query_hijack_attempts_by_policy(&self, policy_id: &str) -> Result<Vec<AmendmentEvent>> {
        todo!()
    }

    /// Return current module parameters.
    ///
    /// Flow:
    ///   1. Read from KV key `"p_acp"`
    ///   2. Deserialize as `AcpParams`
    ///   3. If key not set, return default AcpParams (zero values)
    ///
    /// Reads: params store (KV key `"p_acp"`)
    pub fn query_params(&self) -> Result<AcpParams> {
        Ok(self.get_params())
    }

    // ── Lifecycle hooks ─────────────────────────────────────────────────

    /// End-of-block hook: flag expired registration commitments.
    ///
    /// Called once at the end of every block. Scans all non-expired
    /// commitments and marks any that have exceeded their validity
    /// window as expired. This is the only place expiry transitions
    /// happen — individual queries never mutate expiry state.
    ///
    /// Go instantiates a `CommitmentService` on each call from three
    /// components: the ACP engine (`getACPEngine`), a commitment
    /// repository (`getRegistrationsCommitmentRepository`), and the
    /// service constructor. The service's `FlagExpiredCommitments`
    /// method contains all the logic below.
    ///
    /// Flow:
    ///   1. Build a "now" timestamp from the block context:
    ///      - `block_time`: wall-clock time from the block header
    ///      - `block_height`: current block number
    ///
    ///      (Go: `TimestampFromCtx(ctx)` — can fail on proto
    ///      timestamp conversion)
    ///   2. Get all non-expired commitments via
    ///      `get_non_expired_commitments()` (index scan on
    ///      `expired == false`)
    ///   3. For each non-expired commitment, call
    ///      `commitment.is_expired_against(now)` which delegates to
    ///      `creation_ts.is_after(validity, now)`:
    ///      - If `validity` is a block-count duration:
    ///        `creation_block + validity_blocks < block_height`
    ///      - If `validity` is a wall-clock duration:
    ///        `block_time > creation_time + duration`
    ///      - If `validity` has an unknown/invalid type: panic
    ///
    ///        (Go panics; hub.rs should return an error instead)
    ///   4. For each expired commitment: set `expired = true`
    ///      in-memory, collect into a `processed` list
    ///   5. Write all flagged commitments back via
    ///      `update_commitment()` for each
    ///   6. Return the list of newly-expired commitments
    ///
    ///      (Go caller discards the list — but the keeper method
    ///      returns it for testability)
    ///
    /// Error handling (Go behavior):
    ///   - Timestamp construction failure → return error
    ///   - `get_non_expired_commitments` failure → return error
    ///   - Iterator `Value()` or `Next()` failure → return error
    ///   - `is_expired_against` failure (malformed proto timestamp
    ///     or unknown duration type) → return error (or panic in Go
    ///     for unknown duration)
    ///   - Individual `update_commitment` failure → return error
    ///     (partial writes possible — no transaction rollback in Go)
    ///   - The caller (`AppModule.EndBlock`) logs errors but always
    ///     returns nil — end-blocker errors never halt the chain
    ///
    /// No events emitted. No notifications to affected parties.
    ///
    /// Writes: commitment store (`"commitment/"` prefix) — updates
    /// `expired` field on matching records
    ///
    /// Reads: commitment store (non-expired index scan), block context
    /// (time + height)
    #[allow(unused_variables, clippy::missing_const_for_fn)] // Phase 9 replaces with real logic
    pub fn end_blocker(
        &mut self,
        block_ctx: &BlockExecCtx,
    ) -> Result<Vec<RegistrationsCommitment>> {
        Ok(vec![])
    }

    // ── Storage access methods ──────────────────────────────────────────
    //
    // Key paths below are LOGICAL — they describe what data lives where
    // and what indexes exist. The Go implementation uses raccoondb which
    // adds internal sub-prefixes (`vals/`, `count/`) that are NOT
    // replicated here. hub.rs will define its own key layout when the
    // storage layer is implemented.

    // ── Storage — Params ─────────────────────────────────────────────────

    /// Read module parameters from the KV store.
    ///
    /// Flow:
    ///   1. Read value at fixed KV key `"p_acp"`
    ///   2. If key absent, return default `AcpParams` (Go zero values:
    ///      `policy_command_max_expiration_delta = 0`,
    ///      `registrations_commitment_validity = None` (Go: nil `*Duration`))
    ///      These are NOT the governed defaults (43200, 10 min) — those
    ///      are set via `SetParams` during genesis initialization.
    ///   3. Deserialize stored bytes as `AcpParams` (protobuf encoding
    ///      in Go via gogoproto; hub.rs serialization format TBD)
    ///
    /// Key: `"p_acp"` (fixed, no dynamic component)
    /// Value: serialized `AcpParams`
    /// Direction: read-only
    ///
    /// Panics on corrupt stored data (Go: `MustUnmarshal`).
    /// No validation of deserialized values.
    fn get_params(&self) -> AcpParams {
        self.store
            .get(keys::PARAMS_KEY)
            .map_or_else(AcpParams::default, |bytes| {
                borsh::from_slice(bytes).expect("corrupt params store")
            })
    }

    /// Write module parameters to the KV store.
    ///
    /// Flow:
    ///   1. Serialize `params` as `AcpParams`
    ///   2. Store at fixed KV key `"p_acp"` (upsert — overwrites any
    ///      existing value)
    ///
    /// Key: `"p_acp"` (fixed)
    /// Value: serialized `AcpParams`
    /// Direction: write
    ///
    /// No validation of param values — caller is responsible.
    /// Only possible error is serialization failure.
    fn set_params(&mut self, params: &AcpParams) -> Result<()> {
        let bytes = borsh::to_vec(params).map_err(|e| AcpError::State(e.to_string()))?;
        self.store.insert(keys::PARAMS_KEY.to_vec(), bytes);
        Ok(())
    }

    // ── Storage — Replay cache ───────────────────────────────────────────

    /// Check if a signed policy command has already been processed.
    ///
    /// Flow:
    ///   1. Read value at KV key `"spc_seen/" + payload_id`
    ///      (`payload_id` is SHA-256 of the entire JWS string in JSON
    ///      full serialization format — `{"payload":"...","protected":"...",
    ///      "signature":"..."}` — NOT compact `header.payload.signature`
    ///      format. Go uses `go-jose`'s `FullSerialize()`. 32 bytes.)
    ///   2. If key absent → return false
    ///   3. If stored value is not exactly 8 bytes (corrupt) → delete
    ///      the key and return false (self-healing cleanup)
    ///   4. Decode value as big-endian u64 `expire_height`
    ///   5. If `expire_height < current_height` → delete the key
    ///      (lazy TTL expiration) and return false
    ///   6. Otherwise → return true (command already processed)
    ///
    /// Key: `"spc_seen/" + payload_id` (9-byte prefix + 32-byte hash = 41 bytes)
    /// Value: 8 bytes big-endian u64 (expiration block height)
    /// Direction: read + conditional delete (lazy expiration)
    ///
    /// Silently returns false on KV store errors (no error propagation).
    /// This is the read side of the replay protection cache.
    fn has_seen_signed_policy_cmd(&mut self, payload_id: &[u8], current_height: u64) -> bool {
        let key = keys::signed_policy_cmd_key(payload_id);
        let bytes = match self.store.get(&key) {
            None => return false,
            Some(b) => b.clone(),
        };
        if bytes.len() != 8 {
            self.store.remove(&key);
            return false;
        }
        let expire_height = u64::from_be_bytes(bytes[..8].try_into().expect("8-byte slice"));
        if expire_height < current_height {
            self.store.remove(&key);
            return false;
        }
        true
    }

    /// Record that a signed policy command has been processed.
    ///
    /// Flow:
    ///   1. Check if key `"spc_seen/" + payload_id` already exists
    ///   2. If exists → return error "already processed" (replay rejection).
    ///      Unlike `has_seen_signed_policy_cmd`, this does NOT check
    ///      expiration — raw existence rejects.
    ///   3. Encode `expire_height` as 8 bytes big-endian
    ///   4. Store at `"spc_seen/" + payload_id`
    ///
    /// Key: `"spc_seen/" + payload_id`
    /// Value: 8 bytes big-endian u64 (expiration block height)
    /// Direction: write (with existence check)
    ///
    /// Errors:
    ///   - `AcpError::ReplayDetected` if the payload_id already exists
    ///   - KV store read errors (from existence check) and write errors
    ///     propagate — unlike `has_seen_signed_policy_cmd` which silently
    ///     swallows errors, this method surfaces them
    ///
    /// The `expire_height` is computed by the caller as
    /// `issued_height + expiration_delta`. Together with
    /// `has_seen_signed_policy_cmd`, this forms a replay-protection
    /// cache with lazy TTL cleanup on the read path.
    fn mark_signed_policy_cmd_seen(&mut self, payload_id: &[u8], expire_height: u64) -> Result<()> {
        let key = keys::signed_policy_cmd_key(payload_id);
        if self.store.contains_key(&key) {
            return Err(AcpError::ReplayDetected);
        }
        self.store.insert(key, expire_height.to_be_bytes().to_vec());
        Ok(())
    }

    // ── Storage — Access decisions ───────────────────────────────────────

    /// Store an access decision.
    ///
    /// Flow:
    ///   1. Serialize `decision` (all fields including operations, params,
    ///      creation_time, issued_height)
    ///   2. Store at `"access_decision/" + decision.id`
    ///      (`id` is base32-encoded SHA-256 hash of all decision fields,
    ///      using uppercase RFC 4648 alphabet with `=` padding)
    ///
    /// Key: `"access_decision/" + decision.id` (base32 string key)
    /// Value: serialized `AccessDecision`
    /// Direction: write (upsert)
    ///
    /// The `decision.id` must be pre-computed by the caller before
    /// calling this method — the repository does not generate the ID.
    /// Called by `check_access` after a successful Zanzibar evaluation.
    fn set_access_decision(&mut self, decision: &AccessDecision) -> Result<()> {
        let key = keys::access_decision_key(&decision.id);
        let bytes = borsh::to_vec(decision).map_err(|e| AcpError::State(e.to_string()))?;
        self.store.insert(key, bytes);
        Ok(())
    }

    /// Fetch an access decision by its ID.
    ///
    /// Flow:
    ///   1. Read value at `"access_decision/" + id`
    ///   2. If key absent → return `None` (not an error)
    ///   3. Deserialize as `AccessDecision`
    ///
    /// Key: `"access_decision/" + id`
    /// Value: serialized `AccessDecision`
    /// Direction: read-only
    ///
    /// Missing decision returns `Ok(None)`, not an error.
    /// Deserialization failure on an existing key returns `Err`, not `None`.
    /// Called by `query_access_decision`.
    fn get_access_decision(&self, id: &str) -> Result<Option<AccessDecision>> {
        let key = keys::access_decision_key(id);
        match self.store.get(&key) {
            None => Ok(None),
            Some(bytes) => {
                let decision: AccessDecision =
                    borsh::from_slice(bytes).map_err(|e| AcpError::State(e.to_string()))?;
                Ok(Some(decision))
            }
        }
    }

    /// Delete an access decision by its ID.
    ///
    /// Flow:
    ///   1. Delete key `"access_decision/" + id`
    ///
    /// Key: `"access_decision/" + id`
    /// Direction: delete
    ///
    /// Deleting a non-existent key is a no-op (not an error).
    fn delete_access_decision(&mut self, id: &str) -> Result<()> {
        self.store.remove(&keys::access_decision_key(id));
        Ok(())
    }

    /// List all access decision IDs.
    ///
    /// Flow:
    ///   1. Iterate all keys under prefix `"access_decision/"`
    ///   2. Collect the key suffixes (the decision IDs) as strings
    ///
    /// Key prefix: `"access_decision/"`
    /// Direction: read-only (full prefix scan, keys only)
    ///
    /// Returns empty vec if no decisions exist.
    fn list_access_decision_ids(&self) -> Result<Vec<String>> {
        let prefix = keys::ACCESS_DECISION_PREFIX;
        let ids = self
            .store
            .keys()
            .filter(|k| k.starts_with(prefix))
            .map(|k| String::from_utf8_lossy(&k[prefix.len()..]).into_owned())
            .collect();
        Ok(ids)
    }

    /// List all access decisions.
    ///
    /// Flow:
    ///   1. Iterate all key-value pairs under prefix `"access_decision/"`
    ///   2. Deserialize each value as `AccessDecision`
    ///   3. If any single record fails to deserialize, return error
    ///      immediately (all-or-nothing)
    ///
    /// Key prefix: `"access_decision/"`
    /// Direction: read-only (full prefix scan, keys + values)
    ///
    /// Returns empty vec if no decisions exist.
    fn list_access_decisions(&self) -> Result<Vec<AccessDecision>> {
        let prefix = keys::ACCESS_DECISION_PREFIX;
        let mut decisions = Vec::new();
        for (key, value) in &self.store {
            if key.starts_with(prefix) {
                let decision: AccessDecision =
                    borsh::from_slice(value).map_err(|e| AcpError::State(e.to_string()))?;
                decisions.push(decision);
            }
        }
        Ok(decisions)
    }

    // ── Storage — Commitments ────────────────────────────────────────────

    /// Create a new registration commitment with an auto-assigned ID.
    ///
    /// Flow:
    ///   1. Read auto-increment counter at `"commitment/counter/id"`
    ///      (0 if absent)
    ///   2. Assign `commitment.id = counter + 1`
    ///   3. Serialize and store at `"commitment/objs/" + BE(id)`
    ///      (key is 8-byte big-endian u64)
    ///   4. Update secondary index for `expired` field:
    ///      store at `"commitment/indexes/expired/idx/" + bool_byte + "/" + BE(id)`
    ///      (bool_byte: 0x00 for false, 0x01 for true)
    ///   5. Update secondary index for `commitment` field:
    ///      store at `"commitment/indexes/commitment/idx/" + commitment_bytes + "/" + BE(id)`
    ///      (commitment_bytes: 32-byte SHA-256 Merkle root)
    ///   6. Increment counter by 1 (counter now equals `id`)
    ///
    /// Keys written:
    ///   - `"commitment/counter/id"` (auto-increment counter)
    ///   - `"commitment/objs/" + BE(id)` (object data)
    ///   - `"commitment/indexes/expired/idx/" + bool + "/" + BE(id)` (expired index)
    ///   - `"commitment/indexes/commitment/idx/" + bytes + "/" + BE(id)` (commitment index)
    ///
    /// Direction: write (insert only, never overwrites existing)
    ///
    /// Called by `direct_policy_cmd` CommitRegistrations variant.
    /// New commitments always have `expired = false`.
    fn create_commitment(&mut self, commitment: &mut RegistrationsCommitment) -> Result<()> {
        let counter_key = keys::commitment_counter_key();
        let counter = self
            .store
            .get(&counter_key)
            .and_then(|b| b.as_slice().try_into().ok())
            .map_or(0u64, u64::from_be_bytes);
        let new_id = counter + 1;
        commitment.id = new_id;

        let bytes = borsh::to_vec(&*commitment).map_err(|e| AcpError::State(e.to_string()))?;
        self.store.insert(keys::commitment_key(new_id), bytes);
        self.store.insert(
            keys::commitment_expired_index_key(commitment.expired, new_id),
            vec![],
        );
        self.store.insert(
            keys::commitment_by_commitment_index_key(&commitment.commitment, new_id),
            vec![],
        );
        self.store
            .insert(counter_key, new_id.to_be_bytes().to_vec());
        Ok(())
    }

    /// Update an existing registration commitment in place.
    ///
    /// Flow:
    ///   1. Read existing record at `"commitment/objs/" + BE(commitment.id)`
    ///   2. Remove old record from secondary indexes (extract old field
    ///      values, remove from old index buckets)
    ///   3. Serialize and store updated record at same key
    ///   4. Add new record to secondary indexes with new field values
    ///
    /// Keys written:
    ///   - `"commitment/objs/" + BE(id)` (overwritten)
    ///   - expired index entries (old removed, new added)
    ///   - commitment index entries (old removed, new added)
    ///
    /// Direction: write (in-place update)
    ///
    /// Primary use case: transitioning `expired` from false to true.
    /// When expired changes, the record moves from the `expired=false`
    /// index bucket to the `expired=true` bucket, so
    /// `get_non_expired_commitments` stops returning it.
    /// Does NOT change the auto-increment counter.
    fn update_commitment(&mut self, commitment: &RegistrationsCommitment) -> Result<()> {
        let obj_key = keys::commitment_key(commitment.id);
        let old_bytes =
            self.store.get(&obj_key).cloned().ok_or_else(|| {
                AcpError::State(format!("commitment {} not found", commitment.id))
            })?;
        let old: RegistrationsCommitment =
            borsh::from_slice(&old_bytes).map_err(|e| AcpError::State(e.to_string()))?;

        self.store.remove(&keys::commitment_expired_index_key(
            old.expired,
            commitment.id,
        ));
        self.store.remove(&keys::commitment_by_commitment_index_key(
            &old.commitment,
            commitment.id,
        ));

        let bytes = borsh::to_vec(commitment).map_err(|e| AcpError::State(e.to_string()))?;
        self.store.insert(obj_key, bytes);
        self.store.insert(
            keys::commitment_expired_index_key(commitment.expired, commitment.id),
            vec![],
        );
        self.store.insert(
            keys::commitment_by_commitment_index_key(&commitment.commitment, commitment.id),
            vec![],
        );
        Ok(())
    }

    /// Fetch a registration commitment by its auto-increment ID.
    ///
    /// Flow:
    ///   1. Read value at `"commitment/objs/" + BE(id)` (8-byte big-endian key)
    ///   2. If absent → return `None`
    ///   3. Deserialize as `RegistrationsCommitment`
    ///
    /// Key: `"commitment/objs/" + BE(id)`
    /// Value: serialized `RegistrationsCommitment`
    /// Direction: read-only
    ///
    /// Missing record returns `Ok(None)`, not an error.
    fn get_commitment_by_id(&self, id: u64) -> Result<Option<RegistrationsCommitment>> {
        match self.store.get(&keys::commitment_key(id)) {
            None => Ok(None),
            Some(bytes) => {
                let c: RegistrationsCommitment =
                    borsh::from_slice(bytes).map_err(|e| AcpError::State(e.to_string()))?;
                Ok(Some(c))
            }
        }
    }

    /// Find commitments matching a commitment byte value (Merkle root).
    ///
    /// Flow:
    ///   1. Scan secondary index `"commitment/indexes/commitment/idx/" + commitment_bytes + "/"`
    ///      to get matching object keys (8-byte IDs)
    ///   2. For each key, fetch and deserialize the full record from
    ///      `"commitment/objs/" + key`
    ///
    /// Key prefix scanned: `"commitment/indexes/commitment/idx/" + commitment_bytes + "/"`
    /// Direction: read-only (index scan + object materialization)
    ///
    /// Returns empty iterator/vec if no matches.
    /// Multiple commitments can share the same Merkle root (different
    /// actors or policies committing the same set of registrations).
    fn filter_commitments_by_commitment(
        &self,
        commitment: &[u8],
    ) -> Result<Vec<RegistrationsCommitment>> {
        let prefix = keys::commitment_by_commitment_index_prefix(commitment);
        let ids: Vec<u64> = self
            .store
            .keys()
            .filter(|k| k.starts_with(&prefix))
            .map(|k| u64::from_be_bytes(k[k.len() - 8..].try_into().expect("8-byte id suffix")))
            .collect();
        let mut results = Vec::new();
        for id in ids {
            if let Some(c) = self.get_commitment_by_id(id)? {
                results.push(c);
            }
        }
        Ok(results)
    }

    /// Get all non-expired registration commitments.
    ///
    /// Flow:
    ///   1. Scan secondary index `"commitment/indexes/expired/idx/" + 0x00 + "/"`
    ///      (bucket for `expired = false`)
    ///   2. For each key, fetch and deserialize the full record from
    ///      `"commitment/objs/" + key`
    ///
    /// Key prefix scanned: `"commitment/indexes/expired/idx/0x00/"`
    /// Direction: read-only (index scan + object materialization)
    ///
    /// Returns empty iterator/vec if all commitments are expired.
    ///
    /// This method only returns records where `expired == false` — it
    /// does NOT perform any expiry check itself. The expiry check lives
    /// in a separate end-of-block sweep (`FlagExpiredCommitments` in Go)
    /// which:
    ///   1. Calls this method to get all non-expired commitments
    ///   2. For each, checks `creation_ts + validity < now`
    ///   3. Calls `update_commitment` to set `expired = true`
    ///
    /// Expiry supports two duration modes:
    ///   - Block count: `creation_block_height + block_count < current_height`
    ///   - Wall-clock: `current_time > creation_time + duration`
    ///
    /// Default validity is 10 minutes wall-clock (stored per-record in
    /// the `validity` field at creation time, not recomputed from defaults).
    fn get_non_expired_commitments(&self) -> Result<Vec<RegistrationsCommitment>> {
        let prefix = keys::commitment_expired_index_prefix(false);
        let ids: Vec<u64> = self
            .store
            .keys()
            .filter(|k| k.starts_with(&prefix))
            .map(|k| u64::from_be_bytes(k[k.len() - 8..].try_into().expect("8-byte id suffix")))
            .collect();
        let mut results = Vec::new();
        for id in ids {
            if let Some(c) = self.get_commitment_by_id(id)? {
                results.push(c);
            }
        }
        Ok(results)
    }

    // ── Storage — Amendment events ───────────────────────────────────────

    /// Create a new amendment event with an auto-assigned ID.
    ///
    /// Flow:
    ///   1. Read auto-increment counter at `"amendment_event/counter/id"`
    ///      (0 if absent)
    ///   2. Assign `event.id = counter + 1`
    ///   3. Serialize and store at `"amendment_event/objs/" + BE(id)`
    ///   4. Update secondary index for `policy_id` field:
    ///      store at `"amendment_event/indexes/policy/idx/" + policy_id + "/" + BE(id)`
    ///   5. Increment counter to `id`
    ///
    /// Keys written:
    ///   - `"amendment_event/counter/id"` (auto-increment counter)
    ///   - `"amendment_event/objs/" + BE(id)` (object data)
    ///   - `"amendment_event/indexes/policy/idx/" + policy_id + "/" + BE(id)` (policy index)
    ///
    /// Direction: write (insert only)
    ///
    /// Called by `direct_policy_cmd` RevealRegistration variant when
    /// an ownership amendment occurs (commitment is older than existing
    /// registration). New events always have `hijack_flag = false`.
    fn create_amendment_event(&mut self, event: &mut AmendmentEvent) -> Result<()> {
        let counter_key = keys::amendment_event_counter_key();
        let counter = self
            .store
            .get(&counter_key)
            .and_then(|b| b.as_slice().try_into().ok())
            .map_or(0u64, u64::from_be_bytes);
        let new_id = counter + 1;
        event.id = new_id;

        let bytes = borsh::to_vec(&*event).map_err(|e| AcpError::State(e.to_string()))?;
        self.store.insert(keys::amendment_event_key(new_id), bytes);
        self.store.insert(
            keys::amendment_event_policy_index_key(&event.policy_id, new_id),
            vec![],
        );
        self.store
            .insert(counter_key, new_id.to_be_bytes().to_vec());
        Ok(())
    }

    /// Update an existing amendment event in place.
    ///
    /// Flow:
    ///   1. Read existing record at `"amendment_event/objs/" + BE(event.id)`
    ///   2. Remove old record from policy index (extract old policy_id,
    ///      remove from old bucket)
    ///   3. Serialize and store updated record at same key
    ///   4. Add new record to policy index with new policy_id
    ///
    /// Keys written:
    ///   - `"amendment_event/objs/" + BE(id)` (overwritten)
    ///   - policy index entries (old removed, new added — though in
    ///     practice policy_id never changes between updates)
    ///
    /// Direction: write (in-place update)
    ///
    /// Primary use case: setting `hijack_flag = true` via the
    /// FlagHijackEvent service method (called from the
    /// FlagHijackAttempt policy command variant). Does NOT change
    /// the auto-increment counter.
    fn update_amendment_event(&mut self, event: &AmendmentEvent) -> Result<()> {
        let obj_key = keys::amendment_event_key(event.id);
        let old_bytes =
            self.store.get(&obj_key).cloned().ok_or_else(|| {
                AcpError::State(format!("amendment event {} not found", event.id))
            })?;
        let old: AmendmentEvent =
            borsh::from_slice(&old_bytes).map_err(|e| AcpError::State(e.to_string()))?;

        self.store.remove(&keys::amendment_event_policy_index_key(
            &old.policy_id,
            event.id,
        ));

        let bytes = borsh::to_vec(event).map_err(|e| AcpError::State(e.to_string()))?;
        self.store.insert(obj_key, bytes);
        self.store.insert(
            keys::amendment_event_policy_index_key(&event.policy_id, event.id),
            vec![],
        );
        Ok(())
    }

    /// Fetch an amendment event by its auto-increment ID.
    ///
    /// Flow:
    ///   1. Read value at `"amendment_event/objs/" + BE(id)`
    ///   2. If absent → return `None`
    ///   3. Deserialize as `AmendmentEvent`
    ///
    /// Key: `"amendment_event/objs/" + BE(id)`
    /// Value: serialized `AmendmentEvent`
    /// Direction: read-only
    ///
    /// Missing record returns `Ok(None)`, not an error.
    fn get_amendment_event_by_id(&self, id: u64) -> Result<Option<AmendmentEvent>> {
        match self.store.get(&keys::amendment_event_key(id)) {
            None => Ok(None),
            Some(bytes) => {
                let event: AmendmentEvent =
                    borsh::from_slice(bytes).map_err(|e| AcpError::State(e.to_string()))?;
                Ok(Some(event))
            }
        }
    }

    /// List all amendment events for a given policy.
    ///
    /// Flow:
    ///   1. Scan secondary index
    ///      `"amendment_event/indexes/policy/idx/" + policy_id + "/"`
    ///      to get matching object keys (8-byte IDs)
    ///   2. For each key, fetch and deserialize the full record from
    ///      `"amendment_event/objs/" + key`
    ///
    /// Key prefix scanned: `"amendment_event/indexes/policy/idx/" + policy_id + "/"`
    /// Direction: read-only (index scan + object materialization)
    ///
    /// Returns empty vec if no events exist for this policy.
    fn list_events_by_policy(&self, policy_id: &str) -> Result<Vec<AmendmentEvent>> {
        let prefix = keys::amendment_event_policy_index_prefix(policy_id);
        let ids: Vec<u64> = self
            .store
            .keys()
            .filter(|k| k.starts_with(&prefix))
            .map(|k| u64::from_be_bytes(k[k.len() - 8..].try_into().expect("8-byte id suffix")))
            .collect();
        let mut results = Vec::new();
        for id in ids {
            if let Some(event) = self.get_amendment_event_by_id(id)? {
                results.push(event);
            }
        }
        Ok(results)
    }

    /// List amendment events flagged as hijack attempts for a policy.
    ///
    /// Flow:
    ///   1. Call `list_events_by_policy(policy_id)` to get all events
    ///      for the policy via the secondary index
    ///   2. Filter in-memory to events where `hijack_flag == true`
    ///
    /// Direction: read-only (delegates to `list_events_by_policy` +
    ///   application-level filter)
    ///
    /// There is no secondary index on `hijack_flag` — this scans ALL
    /// events for the policy and filters in memory. If the volume of
    /// amendment events per policy becomes large, consider adding a
    /// composite index.
    ///
    /// A "hijack event" is an `AmendmentEvent` where an ownership
    /// amendment occurred and the new owner (whose commitment was older)
    /// flagged the event to indicate the previous owner may have tried
    /// to register an object already committed by someone else.
    fn list_hijack_events_by_policy(&self, policy_id: &str) -> Result<Vec<AmendmentEvent>> {
        Ok(self
            .list_events_by_policy(policy_id)?
            .into_iter()
            .filter(|e| e.hijack_flag)
            .collect())
    }

    // ── Engine factory ───────────────────────────────────────────────────

    /// Construct a fresh ACP engine instance from the current state.
    ///
    /// Flow:
    ///   1. Open the module's KV store (scoped to `"acp"` module prefix).
    ///      No additional prefix is applied at this level — unlike the
    ///      repository factories which add their own prefixes, the engine
    ///      receives the raw module store.
    ///   2. Adapt the KV store to the engine's expected interface (Go:
    ///      two adapter steps from Cosmos core KV → storetypes.KVStore
    ///      → raccoondb.KVStore; hub.rs will need its own bridge from
    ///      QMDB to whatever the Rust engine expects)
    ///   3. Construct a `RuntimeManager` with:
    ///      - The adapted KV store (engine internally sub-prefixes into
    ///        `"store/"` for main state and `"internal/"` for bookkeeping)
    ///      - A time service that reads block time from execution context
    ///        (must carry block time, not wall-clock — the context flowing
    ///        through the engine's method calls must have the correct
    ///        block timestamp)
    ///   4. Wrap the runtime in an `EngineService` (a dispatcher that
    ///      delegates each operation to internal handler packages which
    ///      implement Zanzibar relation-tuple semantics)
    ///
    /// The engine is stateless — it is a lightweight wrapper around a
    /// KV store reference, reconstructed per-request. Each internal
    /// handler constructs a fresh Zanzibar adapter from the same KV.
    /// All state lives in the KV store; the engine is a stateless
    /// interpreter over that store. The Go keeper may construct the
    /// engine multiple times within a single request (once per service
    /// that needs it).
    ///
    /// The engine interface exposes:
    ///   - Policy CRUD: create, create_with_specification, edit,
    ///     edit_metadata, delete, get, get_catalogue, list, validate
    ///   - Relationship management: set, delete, filter
    ///   - Object lifecycle: register, archive, unarchive, transfer,
    ///     get_registration, amend_registration, reveal_registration
    ///   - Access verification: verify_access_request,
    ///     check_management_authority, evaluate_theorem
    ///   - Params: get/set (engine-level, separate from module params)
    ///
    /// The engine's policy store, relationship store, and object
    /// registration store all live under the `"store/"` sub-prefix
    /// within the module's KV namespace. The Zanzibar graph engine
    /// further partitions within `"store/"` for policy data and
    /// relation nodes.
    ///
    /// Go panics on construction failure. hub.rs should return `Result`.
    fn get_acp_engine(&self) {
        todo!()
    }
}
